name: Release
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build PanCardView --configuration Release
      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-output
          path: ./PanCardView/bin/Release/
